version: "3.1"
services:
  web:
    image: nginx:latest
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
  php:
    build:
      context: ./php-container
      dockerfile: Dockerfile
    volumes:
      - ./code:/code
